let express=require('express')
let mongoose=require('mongoose')
let cors=require('cors')
const userroute = require('./routes/userroutes')
const prodroute = require('./routes/prodroutes')
const cartroute = require('./routes/cartroutes')
let app=express()
app.use(express.json())
app.use(cors())
app.use("/imgs",express.static("./prodimgs"))
mongoose.connect("mongodb://127.0.0.1:27017/newecomapp").then(()=>{
    console.log("ok")
}).catch((err)=>console.log("mongodb error"))
app.use("/user",userroute)
app.use("/prod",prodroute)
app.use("/cart",cartroute)
app.listen(5000)